# - Try to find 3Voda library
# Once done this will define 
# 
#  A3VODA_FOUND - system has 3Voda library
#  A3VODA_INCLUDE_DIR - the 3Voda include directory
#  A3VODA_LIBRARIES - Link these to use 3Voda library
#
include(CheckCXXSourceCompiles)

IF (A3VODA_INCLUDE_DIR AND A3VODA_LIBRARIES)
    # Already in cache, be silent
    SET(A3VODA_FIND_QUIETLY TRUE)
ENDIF (A3VODA_INCLUDE_DIR AND A3VODA_LIBRARIES)

FIND_PATH(A3VODA_INCLUDE_DIR MQTTWrapper.h PATH_SUFFIXES a3voda)
FIND_LIBRARY(A3VODA_LIBRARIES NAMES a3voda liba3voda)

IF(A3VODA_INCLUDE_DIR AND A3VODA_LIBRARIES)
    SET(A3VODA_FOUND TRUE)
ENDIF(A3VODA_INCLUDE_DIR AND A3VODA_LIBRARIES)

IF(A3VODA_FOUND)
    IF(NOT A3VODA_FIND_QUIETLY)
        MESSAGE(STATUS "Found 3Voda library: ${A3VODA_LIBRARIES}")
    ENDIF(NOT A3VODA_FIND_QUIETLY)
ELSE(A3VODA_FOUND)
    IF(A3voda_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find 3Voda library")
    ENDIF(A3voda_FIND_REQUIRED)
ENDIF(A3VODA_FOUND)

MARK_AS_ADVANCED(
        A3VODA_INCLUDE_DIR
        A3VODA_LIBRARIES
)
